<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title> 02-Promise的链式调用 </title>
</head>

<body>
  <script>
    /**
     * 网络请求: aaa -> 自己处理(10 行)
     * 处理: aaa 111 -> (后面拼接 111)
     * 网络请求: aaa 111 -> 自己处理(10 行)
     * 处理: aaa 111 222 -> (后面拼接 222)
     */

    // 0.
    /* let promise = new Promise((resolve, reject) => {
      setTimeout(() => {
        resolve('aaa')
      }, 1000);
    }).then(res => {
      console.info(res, '第一层十行处理代码');
      return new Promise((resolve, reject) => {
        setTimeout(() => {
          resolve(res + 111);
        }, 1000);
      }).then(res => {
        console.info(res, '第二层十行处理代码');
        return new Promise((resolve, reject) => {
          setTimeout(() => {
            resolve(res + 222);
          }, 1000);
        }).then(res => {
          console.info(res, '第三层十行处理代码');
        });
      });
    }); */

    // 1.
    /* let promise = new Promise((resolve, reject) => {
      setTimeout(() => {
        resolve('aaa')
      }, 1000);
    }).then(res => {
      console.info(res, '第一层十行处理代码');
      return Promise.resolve(res + 111)
    }).then(res => {
      console.info(res, '第二层十行处理代码');
      return Promise.resolve(res + 222)
    }).then(res => {
      console.info(res, '第三层')
    }); */

    // 2.
    /* let promise = new Promise((resolve, reject) => {
      setTimeout(() => {
        // resolve('aaa');
        reject('err');
      }, 1000);
    }).then(res => {
      console.info(res, '第一层十行处理代码');
      return res + 111 // 内部会进进行一个 Promise 的包装
    }).then(res => {
      console.info(res, '第二层十行处理代码');
      return res + 222
    }).then(res => {
      console.info(res, '第三层')
    }).catch(err => {
      console.info(err)
    }); */

    // 3.
    let promise = new Promise((resolve, reject) => {
      setTimeout(() => {
        resolve('aaa');
        // reject('err');
      }, 1000);
    }).then(res => {
      console.info(res, '第一层十行处理代码');
      // return promise.reject('err') // 内部会进进行一个 Promise 的包装
      // throw '第一层 err messsge'
    }).then(res => {
      console.info(res, '第二层十行处理代码');
      throw '第二层 err messsge'
      return res + 222
    }).then(res => {
      console.info(res, '第三层')
      throw '第三层 err messsge'
    }).catch(err => {
      console.info(err)
    });

    console.info(promise);
  </script>
</body>

</html>